//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ConsoleApp1.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CalculatorWebServiceSoap", Namespace="http://uacs.gov.mk/webservices")]
    public partial class CalculatorWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddOperationCompleted;
        
        private System.Threading.SendOrPostCallback Add1OperationCompleted;
        
        private System.Threading.SendOrPostCallback SubstrictionOperationCompleted;
        
        private System.Threading.SendOrPostCallback MultiplicationOperationCompleted;
        
        private System.Threading.SendOrPostCallback DivisionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCalculationsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CalculatorWebService() {
            this.Url = global::ConsoleApp1.Properties.Settings.Default.ConsoleApp1_localhost_CalculatorWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddCompletedEventHandler AddCompleted;
        
        /// <remarks/>
        public event Add1CompletedEventHandler Add1Completed;
        
        /// <remarks/>
        public event SubstrictionCompletedEventHandler SubstrictionCompleted;
        
        /// <remarks/>
        public event MultiplicationCompletedEventHandler MultiplicationCompleted;
        
        /// <remarks/>
        public event DivisionCompletedEventHandler DivisionCompleted;
        
        /// <remarks/>
        public event GetCalculationsCompletedEventHandler GetCalculationsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://uacs.gov.mk/webservices/Add3Numbers", RequestElementName="Add3Numbers", RequestNamespace="http://uacs.gov.mk/webservices", ResponseElementName="Add3NumbersResponse", ResponseNamespace="http://uacs.gov.mk/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Add3NumbersResult")]
        public int Add(int firstNumber, int secondNumber, int thirdNumber) {
            object[] results = this.Invoke("Add", new object[] {
                        firstNumber,
                        secondNumber,
                        thirdNumber});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AddAsync(int firstNumber, int secondNumber, int thirdNumber) {
            this.AddAsync(firstNumber, secondNumber, thirdNumber, null);
        }
        
        /// <remarks/>
        public void AddAsync(int firstNumber, int secondNumber, int thirdNumber, object userState) {
            if ((this.AddOperationCompleted == null)) {
                this.AddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddOperationCompleted);
            }
            this.InvokeAsync("Add", new object[] {
                        firstNumber,
                        secondNumber,
                        thirdNumber}, this.AddOperationCompleted, userState);
        }
        
        private void OnAddOperationCompleted(object arg) {
            if ((this.AddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddCompleted(this, new AddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="Add1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://uacs.gov.mk/webservices/Add", RequestElementName="Add", RequestNamespace="http://uacs.gov.mk/webservices", ResponseElementName="AddResponse", ResponseNamespace="http://uacs.gov.mk/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("AddResult")]
        public int Add(int firstNumber, int secondNumber) {
            object[] results = this.Invoke("Add1", new object[] {
                        firstNumber,
                        secondNumber});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Add1Async(int firstNumber, int secondNumber) {
            this.Add1Async(firstNumber, secondNumber, null);
        }
        
        /// <remarks/>
        public void Add1Async(int firstNumber, int secondNumber, object userState) {
            if ((this.Add1OperationCompleted == null)) {
                this.Add1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdd1OperationCompleted);
            }
            this.InvokeAsync("Add1", new object[] {
                        firstNumber,
                        secondNumber}, this.Add1OperationCompleted, userState);
        }
        
        private void OnAdd1OperationCompleted(object arg) {
            if ((this.Add1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Add1Completed(this, new Add1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://uacs.gov.mk/webservices/Substriction", RequestNamespace="http://uacs.gov.mk/webservices", ResponseNamespace="http://uacs.gov.mk/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Substriction(int firstNumber, int secondNumber) {
            object[] results = this.Invoke("Substriction", new object[] {
                        firstNumber,
                        secondNumber});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SubstrictionAsync(int firstNumber, int secondNumber) {
            this.SubstrictionAsync(firstNumber, secondNumber, null);
        }
        
        /// <remarks/>
        public void SubstrictionAsync(int firstNumber, int secondNumber, object userState) {
            if ((this.SubstrictionOperationCompleted == null)) {
                this.SubstrictionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubstrictionOperationCompleted);
            }
            this.InvokeAsync("Substriction", new object[] {
                        firstNumber,
                        secondNumber}, this.SubstrictionOperationCompleted, userState);
        }
        
        private void OnSubstrictionOperationCompleted(object arg) {
            if ((this.SubstrictionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubstrictionCompleted(this, new SubstrictionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://uacs.gov.mk/webservices/Multiplication", RequestNamespace="http://uacs.gov.mk/webservices", ResponseNamespace="http://uacs.gov.mk/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Multiplication(int firstNumber, int secondNumber) {
            object[] results = this.Invoke("Multiplication", new object[] {
                        firstNumber,
                        secondNumber});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void MultiplicationAsync(int firstNumber, int secondNumber) {
            this.MultiplicationAsync(firstNumber, secondNumber, null);
        }
        
        /// <remarks/>
        public void MultiplicationAsync(int firstNumber, int secondNumber, object userState) {
            if ((this.MultiplicationOperationCompleted == null)) {
                this.MultiplicationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMultiplicationOperationCompleted);
            }
            this.InvokeAsync("Multiplication", new object[] {
                        firstNumber,
                        secondNumber}, this.MultiplicationOperationCompleted, userState);
        }
        
        private void OnMultiplicationOperationCompleted(object arg) {
            if ((this.MultiplicationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MultiplicationCompleted(this, new MultiplicationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://uacs.gov.mk/webservices/Division", RequestNamespace="http://uacs.gov.mk/webservices", ResponseNamespace="http://uacs.gov.mk/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Division(int firstNumber, int secondNumber) {
            object[] results = this.Invoke("Division", new object[] {
                        firstNumber,
                        secondNumber});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void DivisionAsync(int firstNumber, int secondNumber) {
            this.DivisionAsync(firstNumber, secondNumber, null);
        }
        
        /// <remarks/>
        public void DivisionAsync(int firstNumber, int secondNumber, object userState) {
            if ((this.DivisionOperationCompleted == null)) {
                this.DivisionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDivisionOperationCompleted);
            }
            this.InvokeAsync("Division", new object[] {
                        firstNumber,
                        secondNumber}, this.DivisionOperationCompleted, userState);
        }
        
        private void OnDivisionOperationCompleted(object arg) {
            if ((this.DivisionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DivisionCompleted(this, new DivisionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://uacs.gov.mk/webservices/GetCalculations", RequestNamespace="http://uacs.gov.mk/webservices", ResponseNamespace="http://uacs.gov.mk/webservices", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetCalculations() {
            object[] results = this.Invoke("GetCalculations", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCalculationsAsync() {
            this.GetCalculationsAsync(null);
        }
        
        /// <remarks/>
        public void GetCalculationsAsync(object userState) {
            if ((this.GetCalculationsOperationCompleted == null)) {
                this.GetCalculationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCalculationsOperationCompleted);
            }
            this.InvokeAsync("GetCalculations", new object[0], this.GetCalculationsOperationCompleted, userState);
        }
        
        private void OnGetCalculationsOperationCompleted(object arg) {
            if ((this.GetCalculationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCalculationsCompleted(this, new GetCalculationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void AddCompletedEventHandler(object sender, AddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void Add1CompletedEventHandler(object sender, Add1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Add1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Add1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void SubstrictionCompletedEventHandler(object sender, SubstrictionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubstrictionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubstrictionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void MultiplicationCompletedEventHandler(object sender, MultiplicationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MultiplicationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MultiplicationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void DivisionCompletedEventHandler(object sender, DivisionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DivisionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DivisionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetCalculationsCompletedEventHandler(object sender, GetCalculationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCalculationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCalculationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591